### ISSUE TITLE
Different behaviour when connecting to HTTP instead of HTTPS

### ISSUE THREAD

**Issue by cgr71ii** [transducens/linguacrawl#2]
Linguacrawl does not have the same behaviour in the case of HTTP or HTTPS in the same domain. The output is identical (despite the detail of connecting either HTTP or HTTPS). My YAML file is:
```
user_agent: 'Mozilla/5.0 (compatible; Bitextor/7 +https://github.com/bitextor/bitextor)'
langs_of_interest: ['en', 'es']
crawl_delay: 5
max_time_per_site: 3600
connection_timeout: 10
max_jobs: 12
accepted_tlds: ['es']
seed_urls: ['http://www.ua.es/']
prefix_filter: ['mailto:']
output_dir: '/home/cristian/Documentos/bitextor/output-linguacrawl'
verbose: True
accepted_content: '(text/html)'
max_folder_tree_depth: 100
max_attempts: 3
scout_steps: 10000
min_langs_in_site: 1
mandatory_lang: 'es'
min_percent_mandatory_lang: 10
url_blacklist: ['wordpress','blogspot','facebook','google','wikipedia','youtube','perehodi','twitter','instagram']
```

The displayed output is:
```
INFO:root:"http[s]://www.ua.es/" added to pending URLs
INFO:root:No robots available for subdomain www.ua.es
INFO:root:Trying (0) to read robots.txt for subdomain www.ua.es
INFO:root:Robots.txt read successfuly for subdomain www.ua.es
INFO:root:Trying to fetch http[s]://www.ua.es/ with user agent Mozilla/5.0 (compatible; Bitextor/7 +https://github.com/bitextor/bitextor). Result: True
INFO:root:Connecting to: http[s]://www.ua.es/
INFO:root:Connection obtained: http[s]://www.ua.es/
INFO:root:Get request set http[s]://www.ua.es/
INFO:root:Response obtained from: http[s]://www.ua.es/
INFO:root:Connection is correct
```

When connecting to HTTPS, I get files in the output folder (`ua.es.bitextor.gz` and `ua.es.warc.gz`). In the case of HTTP, I do not get any file in the output folder.

**Comment by mespla** [comment]
I have tried to reproduce the problem after the last changes. What I get now is:
- in the first case (with HTTP), connection is obtained to the ua.es server. Then, from http://www.ua.es, i get a redirect to https://www.ua.es. After the waiting time, the page is downloaded.
- in the second case (with HTTPS), the connection process is the same, but https://www.ua.es is downloaded directly.
In both cases, after a few seconds, I have two or three documents in the output WARC. Can you confirm that this is the same for you? In that case, we can assume that the issue is fixed.

**Comment by cgr71ii** [comment]
Confirmed, now is working as expected. I get the same behaviour that the one you've described with commit 1ee26e8.
